server:
  port: 8000
message:
  greeting: Hello! Product-service configuration pp 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
management:
  security:
    enabled: false
